// This file will be auto-generated by Supabase CLI
// For now, using a basic type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          role?: string
          created_at?: string
          updated_at?: string
        }
      }
      schools: {
        Row: {
          id: string
          name: string
          county: string | null
          town: string | null
          address: string | null
          phone: string | null
          email: string | null
          head_teacher: string | null
          student_count: number | null
          staff_count: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          county?: string | null
          town?: string | null
          address?: string | null
          phone?: string | null
          email?: string | null
          head_teacher?: string | null
          student_count?: number | null
          staff_count?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          county?: string | null
          town?: string | null
          address?: string | null
          phone?: string | null
          email?: string | null
          head_teacher?: string | null
          student_count?: number | null
          staff_count?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add other tables as needed
      [key: string]: any
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
